version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
    timezone: America/New_York
  open-pull-requests-limit: 99
  labels:
  - dependencies
  - Needs QA
  allow:
  - dependency-type: direct
