inherit_gem:
  panolint: rubocop.yml

AllCops:
  TargetRubyVersion: 2.4 # Keep this in sync with .travis.yml

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false
